#Minecraft server properties
#Sun Jul 26 23:17:40 YEKT 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=easy
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=80
force-gamemode=false
function-permission-level=2
gamemode=adventure
generate-structures=false
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=lobby
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=TkA3QDKnGZYYZhL5i2gp9tk4Exbvn3BScCQ2bjJo
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=10000
max-tick-time=60000
max-world-size=29999984
motd=Blade
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=blade
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://cdn.jsdelivr.net/gh/PrincessXVII/blade-server@9236e6a6c34fdd4b568fe0a63266c0eeb82e3151/resourcepack/BladePack.zip
resource-pack-id=dea0a796-19bd-5b6f-885a-0ad696850e84
resource-pack-prompt={"text"\:"Blade Resource Pack","color"\:"gold"}
resource-pack-sha1=58789f4293b64b6d84c0e40969391186117e2dce
server-ip=
server-port=25565
simulation-distance=4
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=6
white-list=false
