name: ServerSpawnControl
version: 1.0.16
main: dev.systemcrash.spawn.ServerSpawnControlPlugin
api-version: "1.21"
softdepend:
  - BladeMeetups

commands:
  spawn:
    description: Teleport to fixed spawn location
    usage: /spawn
