name: BladeCore
version: 1.0.11
main: dev.systemcrash.blade.BladeCorePlugin
api-version: "1.21"
depend: [LuckPerms]
softdepend: [TAB, PlaceholderAPI, AuthMe]

commands:
  rank:
    description: Set a player's rank
    usage: /rank <player> <group>
    permission: blade.rank.grant
  bladeop:
    description: Grant server operator
    usage: /bladeop <player>
    permission: blade.op.grant
  giveorbs:
    description: Give orbs to a player
    usage: /giveorbs <amount> <player>
    permission: blade.orbs.give
  changepass:
    description: Change AuthMe password
    usage: /changepass <old> <new>
    aliases: [smenaparol]
    permission: blade.changepass

permissions:
  blade.rank.grant:
    default: false
  blade.op.grant:
    default: false
  blade.orbs.give:
    default: op
  blade.changepass:
    default: true
  blade.admin:
    default: op
